name: Generate Articles Index

on:
  push:
    branches:
      - master
    paths:
      - 'articles/**'  # 当articles目录有变化时触发
  workflow_dispatch: # 添加手动触发

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 授予写入仓库的权限
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 使用标准令牌认证

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate articles.json
        run: npm run generate

      - name: Build with Webpack
        run: npm run build

      - name: Copy necessary files to dist
        run: |
          cp index.html dist/
          cp -r assets dist/
          cp -r modules dist/
          cp articles.json dist/
          cp .nojekyll dist/
          if [ -f .htaccess ]; then cp .htaccess dist/; fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist